/*this file is generated by OpenJava system.*/
package it.itc.etoc;

public final class DataFlowInstrumentorOJMI {
	public static final String[][] dict = { { "instantiates", "openjava.mop.Metaclass" } };
}
