/*
 * This code was generated by ojc.
 */
import it.itc.etoc.*;


public class BinaryTree
{

    private BinaryTreeNode root;

    java.lang.String a;

    public BinaryTree()
    {
        trace.add( new java.lang.Integer( 1 ) );
        root = null;
        a = "";
    }

    public void insert( BinaryTreeNode z )
    {
        trace.add( new java.lang.Integer( 2 ) );
        if (root == null) {
            trace.add( new java.lang.Integer( 3 ) );
            root = z;
            if (a == "a") {
                trace.add( new java.lang.Integer( 4 ) );
                a = "b";
            } else {
                trace.add( new java.lang.Integer( 5 ) );
            }
        } else {
            trace.add( new java.lang.Integer( 6 ) );
            root.insert( z );
        }
    }

    public boolean search( java.lang.Comparable x )
    {
        trace.add( new java.lang.Integer( 7 ) );
        if (root == null) {
            trace.add( new java.lang.Integer( 8 ) );
            return false;
        } else {
            trace.add( new java.lang.Integer( 9 ) );
        }
        BinaryTreeNode n = root.search( x );
        if (n != null) {
            trace.add( new java.lang.Integer( 10 ) );
            return true;
        } else {
            trace.add( new java.lang.Integer( 11 ) );
        }
        return false;
    }

    
    static java.util.List trace = new java.util.LinkedList();

    
    public static void newTrace()
    {
        trace = new java.util.LinkedList();
    }

    
    public static java.util.List getTrace()
    {
        return trace;
    }

}
