/*
 * This code was generated by ojc.
 */
import it.itc.etoc.*;


public class ClassStudent
{

    private Student student;

    public ClassStudent( Student student )
    {
        trace.add( new java.lang.Integer( 1 ) );
        this.student = student;
    }

    public java.lang.String changeName( java.lang.String name )
    {
        trace.add( new java.lang.Integer( 2 ) );
        this.student.setName( name );
        return this.student.getName();
    }

    public int updateStudentInfo( java.lang.String name )
    {
        trace.add( new java.lang.Integer( 3 ) );
        if (student == null) {
            trace.add( new java.lang.Integer( 4 ) );
            return 0;
        } else {
            trace.add( new java.lang.Integer( 5 ) );
        }
        student.setAge( 22 );
        student.setName( "Test Name" );
        return 1;
    }

    
    static java.util.List trace = new java.util.LinkedList();

    
    public static void newTrace()
    {
        trace = new java.util.LinkedList();
    }

    
    public static java.util.List getTrace()
    {
        return trace;
    }

}
