/*
 * This code was generated by ojc.
 */
import it.itc.etoc.*;


public class Hello
{

    private int a;

    public Hello( int b )
    {
        a = b;
        b = a;
    }

    public void changeValue( java.lang.String string, int b )
    {
        if (a > 4) {
            if (string == null) {
                string = "test";
            }
            a = b;
            return;
        }
        System.out.println( string );
    }

    
    static java.util.List trace = new java.util.LinkedList();

}
